import {
    SiHtml5,
    SiCss3,
    SiJavascript,
    SiGit,
    SiGithub,
    SiWhatsapp,
    SiInstagram,
    SiLinkedin,
    SiNodedotjs,
    SiReact,
    SiRedux,
    SiMaterialui,
    SiNextdotjs,
    SiPostgresql,
    SiTypescript,
    SiSass,
    SiStyledcomponents,
    SiVuedotjs,
    SiExpress,
    SiSequelize,
    SiQuasar,
    SiGraphql
} from 'react-icons/si';

export const aboutMe = [
    'Desarrollador Full Stack residente en Jujuy - Argentina.',
    'Graduado del Bootcamp de Soy Henry.',
    'Amante de la programación, disfruto mucho trabajar en equipo.',
    'Puedo aportar soluciones óptimas en poco tiempo.',
    'Me encuentro reforzando conocimientos en Next.js y Material UI.',
    // 'Estoy abierto a la relocalización.',
]

export const skill = [
    { name: 'HTML 5', icon: <SiHtml5 />, url: 'https://developer.mozilla.org/es/docs/Web/HTML' },
    { name: 'CSS 3', icon: <SiCss3 />, url: 'https://developer.mozilla.org/es/docs/Web/CSS' },
    { name: 'JavaScript', icon: <SiJavascript />, url: 'https://developer.mozilla.org/es/docs/Web/JavaScript' },
    { name: 'TypeScript', icon: <SiTypescript />, url: 'https://www.typescriptlang.org/' },
    { name: 'React js', icon: <SiReact />, url: 'https://reactjs.org/' },
    // { name: 'React Native', icon: <SiReact />, url: 'https://reactnative.dev/' },
    { name: 'Redux js', icon: <SiRedux />, url: 'https://redux.js.org/' },
    { name: 'Material UI', icon: <SiMaterialui />, url: 'https://mui.com/' },
    // { name: 'SASS', icon: <SiSass />, url: 'https://sass-lang.com/' },
    // { name: 'Styled Components', icon: <SiStyledcomponents />, url: 'https://styled-components.com/' },
    { name: 'Next js', icon: <SiNextdotjs />, url: 'https://nextjs.org/' },
    // { name: 'Vue js', icon: <SiVuedotjs />, url: 'https://vuejs.org/' },
    // { name: 'Quasar', icon: <SiQuasar />, url: 'https://quasar.dev/' },
    { name: 'Node js', icon: <SiNodedotjs />, url: 'https://nodejs.org/' },
    { name: 'Express js', icon: <SiExpress />, url: 'https://expressjs.com/' },
    // { name: 'GraphQL', icon: <SiGraphql />, url: 'https://graphql.org/' },
    { name: 'PostgreSQL', icon: <SiPostgresql />, url: 'https://www.postgresql.org/' },
    { name: 'Sequelize', icon: <SiSequelize />, url: 'https://sequelize.org/' },
    // { name: 'Git', icon: <SiGit />, url: 'https://git-scm.com/' },
]